In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
immr = pd.read_csv('../data/processed/immr_processed_2019.csv')
immr.head(2)

,id,immr_code,disease,neon_live_male,child_1_4_live_male,child_5_16_live_male,adult_17_49_live_male,adult_50_69_live_male,adult_ab70_live_male,no_age_live_male,...,neon_dead_female,child_1_4_dead_female,child_5_16_dead_female,adult_17_49_dead_female,adult_50_69_dead_female,adult_ab70_dead_female,no_age_dead_female,total_dead_female,group_index,disease_group
0,1,001,Cholera (A00),0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Certain Infectious and Parasitic Diseases
1,2,002,Typhoid and para typhoid fever (A01),5,34,91,145,57,20,0,...,0,0,0,0,0,0,0,0,0,Certain Infectious and Parasitic Diseases

In [3]:
immr['total_live_male'].sum()

3706458

In [4]:
immr['total_male'] = immr['total_live_male'] + immr['total_dead_male']
immr['total_female'] = immr['total_live_female'] + immr['total_dead_female']

In [5]:
total_male_patients_live = immr['total_live_male'].sum()
total_female_patients_live = immr['total_live_female'].sum()

total_male_patients_dead = immr['total_dead_male'].sum()
total_female_patients_dead = immr['total_dead_female'].sum()


all_males = total_male_patients_live + total_male_patients_dead
all_females = total_female_patients_live + total_female_patients_dead

In [6]:
print(f'Total male patients: {all_males}\nTotal Female Patients: {all_females}')

print(f'Ratio between male - female: {all_males / (all_males + all_females)} : {all_females / (all_males + all_females)}')

Total male patients: 3740535
Total Female Patients: 3737325
Ratio between male - female: 0.5002146335983825 : 0.4997853664016176

In [8]:

male_survival_rate = total_male_patients_live /(total_male_patients_live + total_male_patients_dead)
female_survival_rate = total_female_patients_live /(total_female_patients_live + total_female_patients_dead)

print(f'Male survival rate: {male_survival_rate * 100}%\nFemale Survival rate: {female_survival_rate * 100}%')

Male survival rate: 99.0889805870016%
Female Survival rate: 99.33377482557711%

In [9]:
group_sums = immr[['disease_group', 'group_index', 'total_live_male', 'total_dead_male', 'total_live_female', 'total_dead_female']].groupby('disease_group').sum()

In [10]:
group_sums['male_survival_rate'] = group_sums['total_live_male'] / (group_sums['total_live_male'] + group_sums['total_dead_male'])
group_sums['female_survival_rate'] = group_sums['total_live_female'] / (group_sums['total_live_female'] + group_sums['total_dead_female'])
group_sums

,group_index,total_live_male,total_dead_male,total_live_female,total_dead_female,male_survival_rate,female_survival_rate
disease_group,,,,,,,
Certain Conditions Originating in the Perinatal Period,90,25497,652,25951,537,0.975066,0.979727
Certain Infectious and Parasitic Diseases,0,280737,3675,237656,3411,0.987079,0.985850
"Congenital Malformation, deformations and chromosomal abnormalities",96,7600,296,5078,283,0.962513,0.947211
Disease of the Blood and Blood-forming Organs and Certain Disorders involving the Imune Mechanism,8,26015,46,27414,66,0.998235,0.997598
Disease of the Circulatory System,152,207743,9567,190764,7592,0.955975,0.961725
Disease of the Digestive System,140,197843,1829,174246,850,0.990840,0.995146
Disease of the Genitourinary System,156,258412,1938,265897,1207,0.992556,0.995481
Disease of the Musculoskeletal and connctive tissue,72,107365,43,97060,59,0.999600,0.999392
Diseases of ear and mastoid process,21,29950,0,36545,0,1.000000,1.000000
Diseases of the Eye and Adnexa,36,94790,0,93880,0,1.000000,1.000000
Diseases of the Nervous System,55,40250,395,39016,333,0.990282,0.991537
Diseases of the Respiratory System,99,332911,6074,309258,4010,0.982082,0.987199
Diseases of the Skin and Subcutaneous Tissue,22,140825,55,111400,52,0.999610,0.999533
"Endocrine, Nutrional and Metabolic Diseases",51,62977,439,84904,475,0.993077,0.994437
"Injury, Poisoning and Certain Other Consequences of External Causes",414,872299,2111,492312,901,0.997586,0.998173
Mental and Behavioural Disorders,36,34905,0,23875,0,1.000000,1.000000
Neoplasams,34,68315,3462,88387,2834,0.951767,0.968933
Others,57,561308,3105,523442,1921,0.994499,0.996343
"Pregnancy, Childbirth and the Puerperium",182,0,0,503768,41,NaN,0.999919
"Symptems, Signs and Abnormal Clinical and Laboratory findings, not elsewhere classified",170,356716,390,381573,327,0.998908,0.999144

#### most common diseases

In [11]:
#most common diseases
group_sums['total_male'] = group_sums['total_live_male'] + group_sums['total_dead_male']
group_sums['total_female'] = group_sums['total_live_female'] + group_sums['total_dead_female']

for women

In [12]:
most_female_diseases = group_sums.sort_values(by=['total_female'], ascending=False).head(5)[['total_live_female', 'total_dead_female', 'total_female']]
most_female_diseases

,total_live_female,total_dead_female,total_female
disease_group,,,
Others,523442,1921,525363
"Pregnancy, Childbirth and the Puerperium",503768,41,503809
"Injury, Poisoning and Certain Other Consequences of External Causes",492312,901,493213
"Symptems, Signs and Abnormal Clinical and Laboratory findings, not elsewhere classified",381573,327,381900
Diseases of the Respiratory System,309258,4010,313268

In [13]:
group_sums.sort_values(by=['total_dead_female'], ascending=False).head(5)[['total_live_female', 'total_dead_female', 'total_female']]

,total_live_female,total_dead_female,total_female
disease_group,,,
Disease of the Circulatory System,190764,7592,198356
Diseases of the Respiratory System,309258,4010,313268
Certain Infectious and Parasitic Diseases,237656,3411,241067
Neoplasams,88387,2834,91221
Others,523442,1921,525363

In [14]:
group_sums['individual_survival_female'] = group_sums['total_live_female']/(group_sums['total_female'])

In [15]:
group_sums.sort_values(by=['individual_survival_female'], ascending=True).head(5)[['total_live_female', 'total_dead_female', 'total_female', 'individual_survival_female']]

,total_live_female,total_dead_female,total_female,individual_survival_female
disease_group,,,,
"Congenital Malformation, deformations and chromosomal abnormalities",5078,283,5361,0.947211
Disease of the Circulatory System,190764,7592,198356,0.961725
Neoplasams,88387,2834,91221,0.968933
Certain Conditions Originating in the Perinatal Period,25951,537,26488,0.979727
Certain Infectious and Parasitic Diseases,237656,3411,241067,0.985850

for men

In [16]:
most_male_diseases = group_sums.sort_values(by=['total_male'], ascending=False).head(5)[['total_live_male', 'total_dead_male', 'total_male']]
most_male_diseases

,total_live_male,total_dead_male,total_male
disease_group,,,
"Injury, Poisoning and Certain Other Consequences of External Causes",872299,2111,874410
Others,561308,3105,564413
"Symptems, Signs and Abnormal Clinical and Laboratory findings, not elsewhere classified",356716,390,357106
Diseases of the Respiratory System,332911,6074,338985
Certain Infectious and Parasitic Diseases,280737,3675,284412

In [17]:
group_sums.sort_values(by=['total_dead_male'], ascending=False).head(5)[['total_live_male', 'total_dead_male', 'total_male']]

,total_live_male,total_dead_male,total_male
disease_group,,,
Disease of the Circulatory System,207743,9567,217310
Diseases of the Respiratory System,332911,6074,338985
Certain Infectious and Parasitic Diseases,280737,3675,284412
Neoplasams,68315,3462,71777
Others,561308,3105,564413

In [18]:
group_sums['individual_survival_male'] = group_sums['total_live_male']/(group_sums['total_male'])

In [19]:
group_sums.sort_values(by=['individual_survival_male'], ascending=True).head(5)[['total_live_male', 'total_dead_male', 'total_male', 'individual_survival_male']]

,total_live_male,total_dead_male,total_male,individual_survival_male
disease_group,,,,
Neoplasams,68315,3462,71777,0.951767
Disease of the Circulatory System,207743,9567,217310,0.955975
"Congenital Malformation, deformations and chromosomal abnormalities",7600,296,7896,0.962513
Certain Conditions Originating in the Perinatal Period,25497,652,26149,0.975066
Diseases of the Respiratory System,332911,6074,338985,0.982082

In [52]:
group_sums[group_sums.index == 'Neoplasams '].transpose()

disease_group                Neoplasams
group_index                    34.000000
total_live_male             68315.000000
total_dead_male              3462.000000
total_live_female           88387.000000
total_dead_female            2834.000000
male_survival_rate              0.951767
female_survival_rate            0.968933
total_male                  71777.000000
total_female                91221.000000
individual_survival_female      0.968933
individual_survival_male        0.951767

Child diseases

In [32]:
immr['neon_mortality_rate_male'] = immr['neon_dead_male'] / (immr['neon_live_male'] + immr['neon_dead_male'])
immr['child_14_mortality_rate_male'] = immr['child_1_4_dead_male'] / (immr['child_1_4_live_male'] + immr['child_1_4_dead_male'])
immr['child_516_mortality_rate_male'] = immr['child_5_16_dead_male'] / (immr['child_5_16_live_male'] + immr['child_5_16_dead_male'])

immr['neon_mortality_rate_female'] = immr['neon_dead_female'] / (immr['neon_live_female'] + immr['neon_dead_female'])
immr['child_14_mortality_rate_female'] = immr['child_1_4_dead_female'] / (immr['child_1_4_live_female'] + immr['child_1_4_dead_female'])
immr['child_516_mortality_rate_female'] = immr['child_5_16_dead_female'] / (immr['child_5_16_live_female'] + immr['child_5_16_dead_male'])

In [47]:
selected = 'child_516_mortality_rate_male'
immr.sort_values(by=selected, ascending=False)[['immr_code', 'disease', selected]].head(10)

,immr_code,disease,child_516_mortality_rate_male
76,059,"Malignant neoplasm of trachea, bronchus and lu...",0.272727
42,028,Rabies (A82),0.250000
77,060,Malignant neoplasm of other respiratory and in...,0.250000
25,021,Meningococcal infections (A39),0.100000
160,132,Heart failure (I50),0.086957
162,134,Cerebroavascular disease (I60-I69),0.054945
26,022,"Septicaemia (A40,A41)",0.044747
91,074,Malignant neoplasm of brain (C71),0.043902
133,105,Intracranial and intraspinal abscess and granu...,0.043478
43,029,Viral encephalitis (includes Japanese Encephal...,0.032258

In [39]:
immr['gender_ratio_admit'] = immr['total_live_male']/immr['total_live_female']
immr['gender_ratio_mortal'] = immr['total_dead_male']/immr['total_dead_female']

What are the most male specific diseases 
!! filtering for inf done with < 1000

In [44]:
immr[immr['gender_ratio_admit'] < 1000].sort_values(by='gender_ratio_admit', ascending=False)[['immr_code', 'disease', 'gender_ratio_admit', 'gender_ratio_mortal']].head(10)

,immr_code,disease,gender_ratio_admit,gender_ratio_mortal
123,095,Mental and behavioural disorders due to use of...,18.111111,NaN
75,058,Malignant neoplasm of larnyx (C32),10.243094,15.000000
124,096,Mental and behavioural disorders due to other ...,9.752809,NaN
40,026H,Unspecified sexually transmitted disease (A64),8.333333,NaN
190,162,Alcoholic liver disease (K70),7.839506,10.933333
52,038A,Rubella (B06),7.000000,NaN
159,131,Cor pulmonale (I27.9),4.924731,1.102564
18,015,Leptospirosis (A27),4.800440,2.800000
88,071,Malignant neoplasm of bladder (C67),4.554935,4.750000
67,050,"Malignant neoplasm of lip, oral cavity and pha...",4.362053,4.719512

In [45]:
immr[immr['gender_ratio_mortal'] < 1000].sort_values(by='gender_ratio_mortal', ascending=False)[['immr_code', 'disease', 'gender_ratio_admit', 'gender_ratio_mortal']].head(20)

,immr_code,disease,gender_ratio_admit,gender_ratio_mortal
75,058,Malignant neoplasm of larnyx (C32),10.243094,15.000000
266,236,Toxic effects of other pesticides (T60.1-T60.9),1.513320,14.333333
190,162,Alcoholic liver disease (K70),7.839506,10.933333
49,035,Varicella (Chickenpox) (B01),1.778940,8.000000
177,149,"Bronchitis, emphysema and other chronic obstru...",4.242546,7.668874
265,235,Toxic effects of organophosphate and carbamate...,1.695253,5.050000
19,016,Leprosy (A30),2.993007,5.000000
88,071,Malignant neoplasm of bladder (C67),4.554935,4.750000
67,050,"Malignant neoplasm of lip, oral cavity and pha...",4.362053,4.719512
79,062,Melanoma and other malignant neoplasm of skin ...,1.400000,4.500000
60,043,Mycosis (B35-B49),0.593836,4.000000
10,009A,Other Respiratory Tuberculosis confirmed bacte...,1.717949,4.000000
13,011,Tuberculosis of other organs (A18),1.504348,3.666667
165,137,"Other diseases of arteries, artherosclerosis a...",1.892585,3.400000
260,230,"Other injuries of specified, unspecified and m...",1.998672,3.322148
250,220,"Superficial injury (S00,S10,S20,S30,S40,S50,S6...",2.049035,3.315789
245,215,Senility (R54),0.800416,3.200000
269,239,Other unspecified effects of external causes (...,0.969448,3.117647
193,165,Acute pancreatitis and other diseases of the p...,3.424100,3.032258
138,110,Transient cerebral ischaemic attacks and relat...,1.102236,3.000000